from __future__ import annotations

from pydantic import BaseModel, Field

from app.schemas.contracts import ComplianceLevel, ConversionForecast, CreativeBundle, ScoreBreakdown, ScoreCard


class ComplianceCheckResult(BaseModel):
    level: ComplianceLevel
    risks: list[str] = Field(default_factory=list)
    blocked: bool = False
    reasons: list[str] = Field(default_factory=list)


HIGH_RISK_PATTERNS = {
    "guaranteed cure",
    "instant cure",
    "doctor approved",
    "vet certified",
}
MEDIUM_RISK_PATTERNS = {
    "best ever",
    "no side effects",
    "100% safe",
}
AI_ARTIFACT_PATTERNS = {"as an ai", "chatgpt", "generated by ai", "placeholder"}


def compliance_check(bundle: CreativeBundle) -> ComplianceCheckResult:
    all_text = " ".join(
        [
            " ".join(v.primary_text for v in bundle.copy_variants),
            " ".join(v.headline for v in bundle.copy_variants),
            bundle.video_plan.script,
            bundle.video_plan.hook,
        ]
    ).lower()
    risks: list[str] = []
    reasons: list[str] = []

    high_hits = [p for p in HIGH_RISK_PATTERNS if p in all_text]
    if high_hits:
        risks.append("legal_high_risk")
        reasons.append(f"Detected prohibited medical/legal style claims: {', '.join(high_hits)}")
        return ComplianceCheckResult(level=ComplianceLevel.HIGH, risks=risks, blocked=True, reasons=reasons)

    medium_hits = [p for p in MEDIUM_RISK_PATTERNS if p in all_text]
    ai_hits = [p for p in AI_ARTIFACT_PATTERNS if p in all_text]
    if medium_hits:
        risks.append("legal_medium_risk")
        reasons.append(f"Detected broad claims requiring manual review: {', '.join(medium_hits)}")
    if ai_hits:
        risks.append("ai_artifact_risk")
        reasons.append(f"Detected explicit AI-feel markers: {', '.join(ai_hits)}")

    if medium_hits or ai_hits:
        return ComplianceCheckResult(level=ComplianceLevel.MEDIUM, risks=risks, blocked=False, reasons=reasons)
    return ComplianceCheckResult(level=ComplianceLevel.LOW, risks=risks, blocked=False, reasons=["No major issues."])


def score_bundle(bundle: CreativeBundle, compliance: ComplianceCheckResult) -> tuple[ScoreCard, ConversionForecast]:
    variant_count = max(1, len(bundle.copy_variants))
    avg_copy_length = sum(len(v.primary_text) for v in bundle.copy_variants) / variant_count

    attraction = min(100.0, 58 + variant_count * 2 + len(bundle.video_plan.hook) * 0.08)
    clarity = max(0.0, min(100.0, 88 - abs(avg_copy_length - 90) * 0.45))
    brand_alignment = min(100.0, 65 + len(bundle.video_plan.localization_notes) * 7)
    compliance_score = {"low": 92.0, "medium": 68.0, "high": 20.0}[compliance.level.value]

    ai_artifact_penalty = 0
    text_blob = " ".join(v.primary_text for v in bundle.copy_variants).lower()
    if "!!" in text_blob or "buy now now now" in text_blob:
        ai_artifact_penalty += 20
    if any(marker in text_blob for marker in AI_ARTIFACT_PATTERNS):
        ai_artifact_penalty += 35
    ai_naturalness = max(0.0, 90 - ai_artifact_penalty)

    total_score = (
        attraction * 0.25
        + clarity * 0.20
        + brand_alignment * 0.15
        + compliance_score * 0.25
        + ai_naturalness * 0.15
    )
    total_score = max(0.0, min(100.0, total_score))
    scorecard = ScoreCard(
        sub_scores=ScoreBreakdown(
            attraction=round(attraction, 2),
            clarity=round(clarity, 2),
            brand_alignment=round(brand_alignment, 2),
            compliance=round(compliance_score, 2),
            ai_naturalness=round(ai_naturalness, 2),
        ),
        total_score=round(total_score, 2),
        risk_labels=compliance.risks,
        explanation={
            "attraction": "Hook strength and variant breadth.",
            "clarity": "Copy readability and value proposition precision.",
            "brand_alignment": "Localization and consistent benefit narrative.",
            "compliance": "; ".join(compliance.reasons),
            "ai_naturalness": "Penalty for synthetic-sounding phrasing markers.",
        },
        compliance_level=compliance.level,
        ai_artifact_score=round(ai_naturalness, 2),
    )
    confidence = 0.75 if compliance.level == ComplianceLevel.LOW else 0.55
    if compliance.level == ComplianceLevel.HIGH:
        confidence = 0.35
    forecast = ConversionForecast(
        score_0_100=round(total_score, 2),
        confidence_0_1=confidence,
        drivers=[
            "hook_strength",
            "clarity",
            "compliance_gate",
            "ai_naturalness",
        ],
        recommended_action=(
            "stop_and_rewrite_claims"
            if compliance.level == ComplianceLevel.HIGH
            else "manual_review_before_publish"
            if compliance.level == ComplianceLevel.MEDIUM
            else "approve_for_test_launch"
        ),
    )
    return scorecard, forecast

